name: citystat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.6.4
  package_info_plus: ^8.3.0
  synchronized: ^3.1.0
  fluttertoast: ^8.2.4
  universal_platform: ^1.0.0
  scaled_app: ^1.0.3 
  easy_localization: ^3.0.1
  fixnum: ^1.1.0  
  cross_file: ^0.3.4+1
  flutter_bloc: ^8.1.3
  talker: ^3.2.0
  talker_bloc_logger: ^2.4.0
  path_provider: ^2.1.3
  window_manager: ^0.3.7
  bitsdojo_window: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
