name: citystat_infra_ui_web
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/appflowy-io/appflowy
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter

  citystat_infra_ui_platform_interface:
    path: ../citystat_infra_ui_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CitystatInfraUIPlugin
        fileName: citystat_infra_ui_web.dart
